version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx-cont"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - flask-app
    networks:
      - task-net
  mysql:
    image: mysql:latest
    container_name: mysql-cont
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql
    networks:
      - task-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  flask-app:
    build: .
    image: flask-task-img:latest
    container_name: flask-cont
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql-cont
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - task-net
    restart: always
    prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-cont
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - flask-app
    networks:
      - task-net
    restart: always

networks:
  task-net:
    driver: bridge
